
networks:
  prestashop-network:
    ipam:
      config:
        - subnet: ${PS_NETWORK:-10.76.90.0/24}

volumes:
  db-data:
  shop-composer-dir-cache:
  shop-composer-root-dir-cache:
  shop-npm-dir-cache:

services:
  mariadb:
    image: mariadb:11.4
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWD:-prestashop}
      MARIADB_DATABASE: ${DB_NAME:-prestashop}
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 5s
      timeout: 1s
      retries: 3
    networks:
      prestashop-network:

  prestashop-git:
    hostname: ${PS_HOSTNAME:-localhost}
    build:
      dockerfile: .docker/Dockerfile
      context: ./PrestaShop
      args:
        - VERSION=${VERSION:-8.1-apache}
        - USER_ID=${USER_ID:-1000}
        - GROUP_ID=${GROUP_ID:-1000}
        - NODE_VERSION=${NODE_VERSION:-20.17.0}
        - INSTALL_XDEBUG=${INSTALL_XDEBUG:-false}
    environment:
      DISABLE_MAKE: ${DISABLE_MAKE:-0}
      PS_INSTALL_AUTO: ${PS_INSTALL_AUTO:-1}
      DB_PASSWD: ${DB_PASSWD:-prestashop}
      DB_NAME: ${DB_NAME:-prestashop}
      DB_SERVER: ${DB_SERVER:-mariadb}
      DB_PREFIX: ${DB_PREFIX:-ps_}
      PS_DOMAIN: ${PS_DOMAIN:-ps90.packingpanic.com}
      PS_FOLDER_INSTALL: ${PS_FOLDER_INSTALL:-install-dev}
      PS_FOLDER_ADMIN: ${PS_FOLDER_ADMIN:-admin-dev}
      PS_COUNTRY: ${PS_COUNTRY:-de}
      PS_LANGUAGE: ${PS_LANGUAGE:-en}
      PS_DEV_MODE: ${PS_DEV_MODE:-1}
      PS_ENABLE_SSL: ${PS_ENABLE_SSL:-0}
      PS_ERASE_DB: ${PS_ERASE_DB:-0}
      PS_USE_DOCKER_MAILDEV: ${PS_USE_DOCKER_MAILDEV:-1}
      ADMIN_MAIL: ${ADMIN_MAIL:-demo@prestashop.com}
      ADMIN_PASSWD: ${ADMIN_PASSWD:-Correct Horse Battery Staple}
      BLACKFIRE_ENABLE: ${BLACKFIRE_ENABLE:-0}
      BLACKFIRE_SERVER_ID: ${BLACKFIRE_SERVER_ID:-0}
      BLACKFIRE_SERVER_TOKEN: ${BLACKFIRE_SERVER_TOKEN:-0}
    command: /tmp/docker_run_git.sh
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - ./PrestaShop:/var/www/html
      # make npm and composer directories persistent, so we don't download packages
      # again if we do a reinstall. For some reason the startup script runs composer install as
      # root, so we need to keep /root/.composer as well ;jw
      - shop-composer-root-dir-cache:/root/.composer
      - shop-composer-dir-cache:/var/www/.composer
      - shop-npm-dir-cache:/var/www/.npm
    networks:
      prestashop-network:
        ipv4_address: ${PS_IP:-10.76.90.254}

  maildev:
    image: 'maildev/maildev'
# don't expose ports, we can access it here: http://10.76.90.2:1080    
#    ports:
#      - "1080:1080"
    networks:
      - prestashop-network
